name: Test Project

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: apt update && sudo apt install apache2 -y

      - name: Run apache install status test
        run: systemctl status apache2